title: Dallas-TU
description: CAPSTONE Project Group 

url: http://dallas-tu.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: Dallas-tu
   twitter: Dallas-tu
   facebook: Dallas-tu
   email: Dallas-tu@gmail.com

google_analytics: ""
